#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config focused_border_color "#000000"
bspc config normal_border_color "#000000"
bspc config presel_feedback_color "#E4E4E4"

##autostart
##xrdb ~/.Xresources &
feh --bg-fill $HOME/assets/wp.jpg &
sleep 2 &
exec xbattbar -c top -I maroon -O white -i maroon -o white -t 2 &
succade &
xsetroot -cursor_name left_ptr &
##/etc/xdg/autostart/lxpolkit.desktop &
##lxpolkit &
##pkill mpd-notification
##mpd-notification &
picom &
pkill borders
borders &
